name: Build and deploy ASP.Net Core app to Azure Web App - ProductManagementSystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "${{ runner.tool_cache }}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore ./ProductManagement/ProductManagement.sln

      - name: Build with dotnet
        run: dotnet build ./ProductManagement/ProductManagement.sln --configuration Release

      - name: Apply migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database update --startup-project ./ProductManagement/ProductManagement.csproj --project ./ProductManagement.DAL/ProductManagement.DAL.csproj

      - name: dotnet publish
        run: dotnet publish ./ProductManagement/ProductManagement.sln -c Release -o "${{runner.temp}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{runner.temp}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_28527F4DAA9940A091390CB2A107832F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_08012B3DE5D14BE2BF78FA4C92FDA3FB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_955A284529E84F76B7DEB0B73AA8F3A6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProductManagementSystem'
          slot-name: 'Production'
          package: .
          
